type dye = string;

type dyeSets = dye[];

export const allDyes: dyeSets[] = [
  [
    "Snow White Dye",
    "Ash Grey Dye",
    "Goobbue Grey Dye",
    "Slate Grey Dye",
    "Charcoal Grey Dye",
    "Soot Black Dye",
  ],
  [
    "Rose Pink Dye",
    "Lilac Purple Dye",
    "Rolanberry Red Dye",
    "Dalamud Red Dye",
    "Rust Red Dye",
    "Wine Red Dye",
    "Coral Pink Dye",
    "Blood Red Dye",
    "Salmon Pink Dye",
    "Ruby Red Dye",
    "Cherry Pink Dye",
  ],
  [
    "Sunset Orange Dye",
    "Mesa Red Dye",
    "Bark Brown Dye",
    "Chocolate Brown Dye",
    "Russet Brown Dye",
    "Kobold Brown Dye",
    "Cork Brown Dye",
    "Qiqirn Brown Dye",
    "Opo-opo Brown Dye",
    "Aldgoat Brown Dye",
    "Pumpkin Orange Dye",
    "Acorn Brown Dye",
    "Orchard Brown Dye",
    "Chestnu Brown Dye",
    "Gobbiebag Brown Dye",
    "Shale Brown Dye",
    "Mole Brown Dye",
    "Loam Brown Dye",
  ],
  [
    "Bone White Dye",
    "Ul Brown Dye",
    "Desert Yellow Dye",
    "Honey Yellow Dye",
    "Millioncorn Yellow Dye",
    "Coeurl Yellow Dye",
    "Cream Yellow Dye",
    "Halatali Yellow Dye",
    "Raisin Brown Dye",
    "Canary Yellow Dye",
    "Vanilla Yellow Dye",
  ],
  [
    "Mud Green Dye",
    "Sylph Green Dye",
    "Lime Green Dye",
    "Moss Green Dye",
    "Meadow Green Dye",
    "Olive Green Dye",
    "Marsh Green Dye",
    "Apple Green Dye",
    "Cactuar Green Dye",
    "Hunter Green Dye",
    "Ochu Green Dye",
    "Adamantoise Green Dye",
    "Nophica Green Dye",
    "Deepwood Green Dye",
    "Celeste Green Dye",
    "Turquoise Green Dye",
    "Morbol Green Dye",
  ],
  [
    "Ice Blue Dye",
    "Sky Blue Dye",
    "Seafog Blue Dye",
    "Peacock Blue Dye",
    "Rhotano Blue Dye",
    "Corpse Blue Dye",
    "Ceruleum Blue Dye",
    "Woad Blue Dye",
    "Ink Blue Dye",
    "Raptor Blue Dye",
    "Othard Blue Dye",
    "Storm Blue Dye",
    "Void Blue Dye",
    "Royal Blue Dye",
    "Midnight Blue Dye",
    "Shadow Blue Dye",
    "Abyssal Blue Dye",
    "Dragoon Blue Dye",
    "Turquoise Blue Dye",
  ],
  [
    "Lavender Purple Dye",
    "Gloom Purple Dye",
    "Iris Purple Dye",
    "Grape Purple Dye",
    "Lotus Pink Dye",
    "Colibri Pink Dye",
    "Plum Purple Dye",
    "Regal Purple Dye",
  ],
  [
    "General-purpose Pure White Dye",
    "General-purpose Jet Black Dye",
    "General-purpose  Pastel Pink Dye",
    "General-purpose Dark Red Dye",
    "General-purpose Pastel Green Dye",
    "General-purpose Dark Green Dye",
    "General-purpose Pastel Blue Dye",
    "General-purpose Dark Blue Dye",
    "General-purpose Pastel Purple Dye",
    "General-purpose Dark Purple Dye",
  ],
  [
    "General-purpose Metallic Silver Dye",
    "General-purpose Metallic Gold Dye",
    "General-purpose Metallic Red Dye",
    "General-purpose Metallic Orange Dye",
    "General-purpose Metallic Yellow Dye",
    "General-purpose Metallic Green Dye",
    "General-purpose Metallic Sky Blue Dye",
    "General-purpose Blue Dye",
    "General-purpose Metallic Purple Dye",
    "Gunmetal Black Dye",
    "Pearl White Dye",
    "Metallic Brass Dye",
  ],
];
