type dye = string;

type dyeSets = dye[];

export const allDyes: dyeSets[] = [
  [
    "Snow White Dye",
    "Goobbue Grey Dye",
    "Charcoal Grey Dye",
    "Ash Grey Dye",
    "Slate Grey Dye",
    "Soot Black Dye",
  ],
  [
    "Wine Red Dye",
    "Rolanberry Red Dye",
    "Ruby Red Dye",
    "Dalamud Red Dye",
    "Lilac Purple Dye",
    "Salmon Pink Dye",
    "Coral Pink Dye",
    "Blood Red Dye",
    "Rose Pink Dye",
    "Cherry Pink Dye",
    "Rust Red Dye",
  ],
  [
    "Pumpkin Orange Dye",
    "Mole Brown Dye",
    "Shale Brown Dye",
    "Chestnu Brown Dye",
    "Orchard Brown Dye",
    "Mesa Red Dye",
    "Kobold Brown Dye",
    "Qiqirn Brown Dye",
    "Russet Brown Dye",
    "Loam Brown Dye",
    "Acorn Brown Dye",
    "Cork Brown Dye",
    "Bark Brown Dye",
    "Gobbiebag Brown Dye",
    "Aldgoat Brown Dye",
    "Sunset Orange Dye",
    "Chocolate Brown Dye",
    "Opo-opo Brown Dye",
  ],
  [
    "Ul Brown Dye",
    "Bone White Dye",
    "Canary Yellow Dye",
    "Desert Yellow Dye",
    "Halatali Yellow Dye",
    "Millioncorn Yellow Dye",
    "Honey Yellow Dye",
    "Coeurl Yellow Dye",
    "Raisin Brown Dye",
    "Cream Yellow Dye",
    "Vanilla Yellow Dye",
  ],
  [
    "Adamantoise Green Dye",
    "Meadow Green Dye",
    "Lime Green Dye",
    "Deepwood Green Dye",
    "Olive Green Dye",
    "Ochu Green Dye",
    "Morbol Green Dye",
    "Sylph Green Dye",
    "Turquoise Green Dye",
    "Cactuar Green Dye",
    "Apple Green Dye",
    "Celeste Green Dye",
    "Marsh Green Dye",
    "Mud Green Dye",
    "Nophica Green Dye",
    "Moss Green Dye",
    "Hunter Green Dye",
  ],
  [
    "Midnight Blue Dye",
    "Shadow Blue Dye",
    "Royal Blue Dye",
    "Sky Blue Dye",
    "Void Blue Dye",
    "Rhotano Blue Dye",
    "Abyssal Blue Dye",
    "Woad Blue Dye",
    "Dragoon Blue Dye",
    "Othard Blue Dye",
    "Peacock Blue Dye",
    "Ceruleum Blue Dye",
    "Ink Blue Dye",
    "Ice Blue Dye",
    "Storm Blue Dye",
    "Turquoise Blue Dye",
    "Corpse Blue Dye",
    "Raptor Blue Dye",
    "Seafog Blue Dye",
  ],
  [
    "Colibri Pink Dye",
    "Iris Purple Dye",
    "Gloom Purple Dye",
    "Plum Purple Dye",
    "Grape Purple Dye",
    "Regal Purple Dye",
    "Lotus Pink Dye",
    "Lavender Purple Dye",
  ],
  [
    "General-purpose  Pastel Pink Dye",
    "General-purpose Pastel Purple Dye",
    "General-purpose Dark Green Dye",
    "General-purpose Pure White Dye",
    "General-purpose Dark Red Dye",
    "General-purpose Dark Purple Dye",
    "General-purpose Pastel Blue Dye",
    "General-purpose Dark Blue Dye",
    "General-purpose Pastel Green Dye",
    "General-purpose Jet Black Dye",
  ],
  [
    "General-purpose Blue Dye",
    "General-purpose Metallic Silver Dye",
    "Gunmetal Black Dye",
    "General-purpose Metallic Gold Dye",
    "General-purpose Metallic Yellow Dye",
    "General-purpose Metallic Sky Blue Dye",
    "Metallic Brass Dye",
    "General-purpose Metallic Purple Dye",
    "General-purpose Metallic Green Dye",
    "General-purpose Metallic Red Dye",
    "Pearl White Dye",
    "General-purpose Metallic Orange Dye",
  ],
];
